language: python
python:
  - "3.6"
dist: bionic
env:
  global:
  - TWINE_USERNAME="anthrotype"
  - secure: C1U/VHZkyyCWqDrN7YxEMjo2KDAx1yrnL8hZWffovvpswVd6hffgiXq1VpE1tAn30LZygRLnTqkJpcrwxYJpcBq0J4llJRHlUoeaIwq8WjY+mr6B5FPkkzlpZ39XvzI/EFNdiwlaYyS+5qbAFq1Zi0XBgUd5aD663RbPaOC0WajmmCfOt3kAhz4NyJQyWpC7CrULV1n0MeNXhd4a+iu4Zp+GKFW08ZZsqDipIHHSR7aT3Wbj+u4WANHSHhsrXqaM7291MWv9tEhXeARdXiIRIOeQh77LIIjdmjGUP87yIvVil5sUUPd+jQwxZNY4LfHqgzq/DvCC9ckjkka7owgKiCSPip0rfdzSoM0TOpTUm841q9E87AtTu+guI5P8u78AjbAV8TX2HS/9lb2okTAZYwXAhw26Up32ZKFxSrR2jfOvGsJRMVxKeZkDxyEnuJ3NyP/mSlnzCnsW8kS3yXSB50n7qHCy2mPAjBo2jtyguNFGjf0ucAbyGN4pz8cTtoc5NZsIEQZilPRX6weqzl2F3+n78zpYTDVle8DLLZBntwvw0zsq2wQXuZvyk9v84rFwLPiNxZ9oqZdIyNrz7SvP9boDAv1osImKfc6BrX7DSWG2oEFK8G0AQsQnPR+m1/as9Fajix6JunzMDvnh9cvIIVaKrYwS8eqad63Q8h13lQs=
services:
  # We run "headless" tests with xvfb (X Virtual Framebuffer)
  - xvfb
addons:
  apt:
    packages:
      - libxkbcommon-x11-0  # To make Qt load for tests

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build version tags as well.
    - /^\d+\.\d+.*$/

before_install:
  # Check environment
  - echo $PATH
  - which python3
  - python3 --version
  # Install requirements
  - pip3 install --upgrade setuptools wheel
  - pip3 install --upgrade -r dev-requirements.txt -r requirements.txt
  # Print PyQt5 and SIP versions
  - python -c "import PyQt5.sip as sip; print(sip.__file__); print('sip version:', sip.SIP_VERSION_STR)"
  - python -c "from PyQt5 import Qt; print(Qt.__file__); print('PyQt5 version:', Qt.PYQT_VERSION_STR)"

install:
  - pip3 install .

script:
  - pre-commit run -a
  - pytest

# deploy sdist and wheel packages to PyPI on tags
after_success:
- |
  if [[ $TRAVIS_TAG && $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
    python -m pip install --upgrade pip setuptools setuptools_scm wheel twine
    git fetch --unshallow
    python setup.py sdist bdist_wheel
    python -m twine upload dist/*.zip dist/*.whl
  fi
